# Site wide configuration

title: "Underwrite Your Life"
description: "Finance for the Rest of Us"
logo: #120x120 image used mainly for twitter cards if a large feature image isn't there. upload this to images folder then link here
teaser: /image-alignment-300x200.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: ##
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner:
  name:
  email: 
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: # 160x160 px image for author byline
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
